[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "=0.30.0"
crossterm = "0.29"
spacetimedb-sdk = "1.12.0"
ollama-rs = "0.3.2"
tokio = { version = "1", features = ["full"] }